# Generated by Django 6.1 on 2026-08-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_seen_by_tourist',
            field=models.BooleanField(default=True),
        ),
    ]
